# Generated by Django 4.1 on 2022-08-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('country', models.CharField(blank=True, max_length=60, null=True, verbose_name='country')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date_of_birth')),
                ('state', models.CharField(blank=True, max_length=60, null=True, verbose_name='state')),
                ('city', models.CharField(blank=True, max_length=60, null=True, verbose_name='city')),
                ('zipcode', models.CharField(blank=True, max_length=60, null=True, verbose_name='zipcode')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.CharField(default='0.0.0.0', max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_support_admin', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
                ('recovery_codes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
